<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>GTFS</AssemblyName>
		<PackageId>GTFS</PackageId>
		<Title>GTFS</Title>
		<Authors>budul100</Authors>
		<Description>GTFS read/write library</Description>
		<PackageProjectUrl>https://github.com/OsmSharp/GTFS</PackageProjectUrl>
		<PackageLicenseUrl>https://raw.github.com/OsmSharp/GTFS/master/LICENSE</PackageLicenseUrl>
		<PackageIconUrl>https://raw.github.com/OsmSharp/GTFS/master/icon.bmp</PackageIconUrl>
		<PackageTags>routing,GTFS,transit</PackageTags>
		<PackageVersion>4.0.0</PackageVersion>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
	</ItemGroup>

</Project>
